Tarball compression
yandex/ch-backup pull request #107
Opened 2024-03-04 09:54 UTC by kirillgarbar

Added compression of uploaded and downloaded tarballs using zlib.
Compression stage can be added to other pipelines if needed.

2024-03-04 13:08 UTC, aalexfvk requested changes

2024-03-04 13:08 UTC, aalexfvk commented on ch_backup/compression/zlib.py
> +class ZLIBCompression(BaseCompression):
And, please, add unit test for this class

2024-03-04 13:10 UTC, aalexfvk commented
Try to add type hints for all new code. It is not forced by linters yet, but will help in the future to enable this checking.

2024-03-04 15:51 UTC, kirillgarbar commented on ch_backup/storage/async_pipeline/stages/compression/compress_stage.py
> +        self._buffer = BytesFIFO(buffer_size)
This also means we should not aggregate data until `chunk_size` is reached?

2024-03-04 15:59 UTC, aalexfvk commented on ch_backup/storage/async_pipeline/stages/compression/compress_stage.py
> +        self._buffer = BytesFIFO(buffer_size)
Yes next `ChunkingStage` should do that. This is its responsibility.

2024-03-05 07:32 UTC, aalexfvk commented on ch_backup/backup/metadata/cloud_storage_metadata.py
> +            compression=data.get("compression", True),
Almost done. I meant that we should treat absent of `compression` key in the metadata as `False`, e.g. for existing backups, but use compression for new ones. Now you can just set this default in config.

2024-03-05 12:46 UTC, aalexfvk approved these changes

2024-03-05 12:46 UTC, merged