Deduplicate with ClickHouse table
yandex/ch-backup pull request #159
Opened 2024-06-05 17:14 UTC by kirillgarbar

DedupInfo and DatabaseDedupInfo classes are removed, DedupReferences is used to collect dedup info instead.
Dedup info is collected in clickhouse table, during deduplication another table is created and deduplication is done with JOIN by name and checksum query.
Unit tests are removed due to the need to use running clickhouse server.

2024-06-13 16:21 UTC, aalexfvk requested changes

2024-06-13 16:21 UTC, aalexfvk commented on ch_backup/clickhouse/control.py
> +    ORDER BY name
And here let's add `checksum`

2024-06-13 16:21 UTC, aalexfvk commented on ch_backup/backup/deduplication.py
> +                    table_dedup_info.add(part.name)
Where part names from `table_dedup_info` are used ?

2024-06-13 16:21 UTC, aalexfvk commented on ch_backup/backup/deduplication.py
> +def _create_dedup_references() -> DedupReferences:
`_create_empty_dedup_references` ?

2024-06-15 14:54 UTC, kirillgarbar commented on ch_backup/backup/deduplication.py
> +    dedup_info = _create_dedup_references()
This dict is used [here](https://github.com/yandex/ch-backup/blob/7ce04913e32d553ee8f2d9df3f9e4f7f2dbce1ef/ch_backup/backup/deduplication.py#L184) to check if processed part is already collected for deduplication, for example from previous metadata file. Not sure if it is possible if deduplication works correctly, but this check was there before.
We can use clickhouse table to check that by collecting part's metadata in batch and filtering them with JOIN query.

2024-06-17 06:37 UTC, aalexfvk commented on ch_backup/backup/deduplication.py
> +    dedup_info = _create_dedup_references()
Ok. But let's add a comment about it.

2024-06-17 16:30 UTC, merged