Limiting network traffic rate for uploading stage.
yandex/ch-backup pull request #48
Opened 2023-08-22 13:31 UTC by MikhailBurdukov

2023-08-23 07:53 UTC, aalexfvk requested changes

2023-08-23 07:58 UTC, aalexfvk commented on ch_backup/util.py
> +            self._bucket_last_update = current_time
I think `last_update` must be updated after every replenish

2023-08-23 08:01 UTC, aalexfvk commented on ch_backup/util.py
> +class RateLimiter:
Let's move this class into a separate import module from `util.py`

2023-08-23 08:12 UTC, aalexfvk commented on tests/integration/features/traffic_limiting.feature
> +    CREATE USER test_user IDENTIFIED WITH plaintext_password BY 'password';
Let's test only data table without ACl entites. In my opinion they are complicating test. SImplify as far as possible

2023-08-23 08:15 UTC, aalexfvk commented on tests/integration/features/traffic_limiting.feature
> +        uploading_traffic_limit_retry_time: 33554432
We can use `Examples:` clause to parametrize these both tests to one. Have a look at `deduplication.feature` for example.

2023-08-23 08:33 UTC, aalexfvk commented on tests/unit/test_rate_limiter.py
> +def test_traffic_rate_limiting(content_size, chunk_size, buffer_size):
Let's write comprehensive unit tests only for `RateLimiter` class. 
Testing on pipeline level looks cumbersome and overloaded with irrilevant details.

2023-08-23 15:32 UTC, MikhailBurdukov commented on ch_backup/config.py
> +        # Upper bound of network loading per second on the uploading stage. (bytes/sec)
Fixed

2023-08-23 15:32 UTC, MikhailBurdukov commented on ch_backup/storage/async_pipeline/pipeline_builder.py
> +        traffic_limit_per_sec = stage_config["uploading_traffic_limit"]
Fixed

2023-08-23 15:36 UTC, MikhailBurdukov commented
@aalexfvk, Fixed all requested changes in the last commit.

2023-08-29 11:58 UTC, aalexfvk approved these changes

2023-08-29 12:00 UTC, merged