Thread safe retry for s3.
yandex/ch-backup pull request #82
Opened 2023-10-25 11:21 UTC by MikhailBurdukov

2023-10-26 14:03 UTC, aalexfvk requested changes

2023-10-26 14:03 UTC, aalexfvk commented on ch_backup/storage/engine/s3/s3_retry.py
> +        def call(self, fn, *args, **kwargs):
Consider overriding  `__call__` method

2023-10-26 14:03 UTC, aalexfvk commented on ch_backup/storage/engine/s3/s3_retry.py
> +        def wrapped_f(*args, **kw):
`kwargs` is more common name

2023-10-26 14:03 UTC, aalexfvk commented on tests/unit/utils.py
> +class TimeMocker:
Let's move it to the separate module `time_mocker.py`

2023-10-31 06:35 UTC, aalexfvk commented on ch_backup/storage/engine/s3/s3_retry.py
> +        return uniform(0, min(high_value, self.max_interval))  # nosec
Nevertheless, I think fixed interval backoff is more preferable here. Pay attention on [this](https://github.com/jd/tenacity/blob/310058274ed22a345e9c3917c97b4afd6363d5a5/tenacity/wait.py#L186) suggestion from tenacity. Clickhouse itself uses exponential fixed backoff intervals when requsting S3.

2023-10-31 06:36 UTC, aalexfvk commented on tests/unit/utils.py
> +class TimeMocker:
Forget to delete ?

2023-10-31 06:42 UTC, aalexfvk commented on ch_backup/storage/engine/s3/s3_retry.py
> +    def __call__(self, fn, *args, **kwargs):
Write comment please that an instance of this class can be called from different threads and should be thread safe. For example, here we don't update state of the class (instance variables) and use only local ones.

2023-11-03 10:36 UTC, aalexfvk approved these changes

2023-11-03 17:37 UTC, Alex-Burmak commented
Test failures for `latest` ClickHouse versions don't relate to the changes from this PR. It relates to https://github.com/yandex/ch-backup/issues/84.

 Merging the PR.

2023-11-03 17:37 UTC, merged